AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  online-judge

  Sample SAM Template for online-judge
  
Globals:
  Function:
    MemorySize: 1769
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  ExecuteFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: online-judge-ExecuteFunction
      Timeout: 8
      # we should probably not hardcode this...
      VpcConfig:
        SecurityGroupIds:
          - sg-0bc4a61cfc9289d08
        SubnetIds:
          - subnet-097720d648805d3ed
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: ./execute
      Dockerfile: Dockerfile
  SubmitFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: online-judge-SubmitFunction
      CodeUri: submit/
      Handler: dist/src/app.lambdaHandler
      Runtime: nodejs14.x
      Timeout: 10
      Policies: 
        - LambdaInvokePolicy:
            FunctionName:
              !Ref ExecuteFunction
        - DynamoDBCrudPolicy:
            TableName:
              !Ref StatisticsDynamoDBTable
      Events:
        Execute:
          Type: Api
          Properties:
            Path: /execute
            Method: post
        CreateSubmission:
          Type: Api
          Properties:
            Path: /submissions
            Method: post
        GetSubmission:
          Type: Api
          Properties:
            Path: /submissions/{submissionId}
            Method: get
    Metadata:
      BuildMethod: makefile

  StatisticsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: online-judge-statistics
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName: id
          KeyType: HASH


Outputs:
  ExecuteFunction:
    Description: "Execute Lambda Function ARN"
    Value: !GetAtt ExecuteFunction.Arn
  SubmitFunction:
    Description: "Submit Lambda Function ARN"
    Value: !GetAtt SubmitFunction.Arn
  StatisticsDynamoDBTable:
    Description: "Statistics Dyanmo DB Table ARN"
    Value: !GetAtt StatisticsDynamoDBTable.Arn